# COMMON VARIABLES

target_account = "313198764750"
target_region  = "us-east-1"
target_role    = "terraform-execution-role"
project        = "workspaces"

tags = {
  "Provisioner" = "Terraform"
  "Repository"  = "https://github.com/clearscale-team/virginia-transformers-tf-workspaces"
  "CostCenter"  = "Testing"
  "Owner"       = "ClearScale"
}

default_ou = "OU=Workspace-Prod,DC=vatransformer,DC=com"

# WORKSPACES DEFINITIONS
workspaces = [
  { user_name = "pkumar", bundle_name = "windows-10-performance-10gb-bundle-prod", user_volume = "50" },
  { user_name = "jchawla", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vgupta1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "spathak", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "agarg", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sdesai", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mshah1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "spatni", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nchauhan", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "cseibert", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "bchaudhry", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "kyavuz", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "AQuinones", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "psavar", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "bmukherjee", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "bjanakiraman", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mjacobo", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mrodriguez1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "bsaleh", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "avidja", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "asonawane", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vcontreras", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "kperez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sveera", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "tluck", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "msharma", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "apandey", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "barora", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rsharma1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "amarta", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "asharma", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dlewis", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jmorales", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mnaik", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mcasarez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rcarbajal", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vsingh2", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ekomic", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "trudolph", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ssharma1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mparashar", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nratha1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "yoli", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dsemwal", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jmagu", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sbhuvad", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jsingh", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vtcw9", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "akumar4", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mshah", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mnelson1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ehill", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rkerbyson", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nwhitaker", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "boliver", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "peng10", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "syalla", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "aarredondo", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "amartinez1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "edominguez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "abadhon", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jbarot", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ayadav", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "gmewada", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "gsingh1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "adiaz", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "emartinez3", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "tramirez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vpawar", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mpatel3", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "radhiya", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "pfadke", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "spatel", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nphalake", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nbhatu", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vbustamante", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ngandhi", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jramirez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "narmendariz", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rquinones", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "bcampos", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rcarrillo", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "Gchagoya", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "hsantillan", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sxavier", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mtorres1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dsoto", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jportillo", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "fbayiha", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jnieto", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "asharma2", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "creyes", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "djuarez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "agarcia4", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "kchauhan", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "agupta1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mramirez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dparmar", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dmolinar", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "schennupati", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sales12", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "pmalik", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mpanigrahi", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "averma2", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "nshukla", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dhernandez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "deeng22", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "aperez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "eperez1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "rlopez1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "mahmad", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "hramos", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vgupta", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "varzaga", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "aradhakishnan", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "spokharel", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "averma1", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "kthrinadha", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "gyadagiri", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "dbanks", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "jlimas", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "ahernandezl", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "sgajjala", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "vmartinez", bundle_name = "windows-10-performance-10gb-bundle-prod" },
  { user_name = "weeng05", bundle_name = "windows-10-performance-10gb-bundle-prod" },
]
